// Auto-generated by scripts/build-icons.mjs - do not edit manually

export const iconNames = ["icon-arrow-pagination","icon-arrow","icon-chevron-down","icon-facebook","icon-linkedin","icon-logo","icon-twitter"] as const
export type IconName = (typeof iconNames)[number]
