#!/usr/bin/env node
/**
 * Builds SVG sprite from src/icons/*.svg
 * Output: public/sprite.svg, src/icons/types.ts
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.join(__dirname, '..')
const iconsDir = path.join(rootDir, 'src', 'icons')
const outputSprite = path.join(rootDir, 'public', 'sprite.svg')
const outputTypes = path.join(rootDir, 'src', 'icons', 'types.ts')

const svgFiles = fs
  .readdirSync(iconsDir, { withFileTypes: true })
  .filter((f) => f.isFile() && f.name.endsWith('.svg'))
  .map((f) => f.name)

if (svgFiles.length === 0) {
  console.warn('[build-icons] No SVG files found in src/icons/')
  process.exit(0)
}

const symbols = []
const iconNames = []

for (const file of svgFiles) {
  const name = path.basename(file, '.svg')
  const iconId = `icon-${name}`
  iconNames.push(iconId)

  const svgPath = path.join(iconsDir, file)
  let svgContent = fs.readFileSync(svgPath, 'utf-8')

  // Extract viewBox
  const viewBoxMatch = svgContent.match(/viewBox=["']([^"']+)["']/)
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24'

  // Remove svg wrapper, extract inner content
  const innerMatch = svgContent.match(/<svg[^>]*>([\s\S]*)<\/svg>/i)
  const inner = innerMatch ? innerMatch[1].trim() : svgContent

  symbols.push(`  <symbol id="${iconId}" viewBox="${viewBox}">${inner}</symbol>`)
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:absolute;width:0;height:0;overflow:hidden">
  <defs>
${symbols.join('\n')}
  </defs>
</svg>
`

fs.writeFileSync(outputSprite, sprite, 'utf-8')

const typesContent = `// Auto-generated by scripts/build-icons.mjs - do not edit manually

export const iconNames = ${JSON.stringify(iconNames)} as const
export type IconName = (typeof iconNames)[number]
`

fs.writeFileSync(outputTypes, typesContent, 'utf-8')

console.log(`[build-icons] Generated sprite with ${iconNames.length} icons → public/sprite.svg`)
console.log(`[build-icons] Types → src/icons/types.ts`)
